import React from "react"
import { Download, Play, CheckCircle, Info, Code, Layers, FileText } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { getFullVideoUrl } from "@/utils/formatters"

interface VideoPlayerProps {
  videoPath: string
  topic: string
  extractedParameters?: Record<string, any>
  approach?: Record<string, any>
}

export const VideoPlayer: React.FC<VideoPlayerProps> = ({
  videoPath,
  topic,
  extractedParameters,
  approach,
}) => {
  const fullVideoUrl = getFullVideoUrl(videoPath)

  const handleDownload = async () => {
    try {
      const response = await fetch(fullVideoUrl)
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      const fileName = `${topic.toLowerCase().replace(/[^a-z0-9]/g, "_")}_lesson.mp4`
      a.download = fileName
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (err) {
      // Fallback direct link opening
      window.open(fullVideoUrl, "_blank")
    }
  }

  return (
    <div className="w-full space-y-6 my-6 animate-in fade-in-50 duration-300">
      {/* Main Video Player Card */}
      <Card className="overflow-hidden border-primary/20 shadow-xl bg-card">
        <CardHeader className="flex flex-row items-center justify-between pb-3 bg-muted/30">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Badge variant="success" className="gap-1">
                <CheckCircle className="h-3 w-3" /> Ready
              </Badge>
              <span className="text-xs text-muted-foreground">Manim Animated Output</span>
            </div>
            <CardTitle className="text-xl font-bold">{topic}</CardTitle>
          </div>
          <Button onClick={handleDownload} className="gap-2 shadow-md">
            <Download className="h-4 w-4" /> Download Video
          </Button>
        </CardHeader>
        <CardContent className="p-0">
          <div className="relative aspect-video bg-black flex items-center justify-center overflow-hidden">
            {fullVideoUrl ? (
              <video
                controls
                autoPlay
                className="w-full h-full object-contain"
                src={fullVideoUrl}
              >
                Your browser does not support the video tag.
              </video>
            ) : (
              <div className="text-muted-foreground flex flex-col items-center gap-2">
                <Play className="h-12 w-12 opacity-50" />
                <span>Video stream unavailable</span>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* AI Breakdown Accordion & Tabs */}
      {(extractedParameters || approach) && (
        <Card className="border-border shadow-md">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Info className="h-5 w-5 text-primary" /> AI Pedagogical Analysis Breakdown
            </CardTitle>
            <CardDescription>
              Detailed breakdown generated by the AI Teaching Engine
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="approach">
              <TabsList className="grid grid-cols-2 mb-4">
                <TabsTrigger value="approach" className="gap-2">
                  <Layers className="h-4 w-4" /> Strategy & Approach
                </TabsTrigger>
                <TabsTrigger value="parameters" className="gap-2">
                  <Code className="h-4 w-4" /> Extracted Parameters
                </TabsTrigger>
              </TabsList>

              {/* Approach Tab */}
              <TabsContent value="approach" className="space-y-4">
                {approach ? (
                  <div className="space-y-4 text-sm">
                    {approach.problem_understanding && (
                      <div className="p-4 rounded-lg bg-muted/40 border">
                        <h4 className="font-semibold text-primary mb-1 flex items-center gap-2">
                          <FileText className="h-4 w-4" /> Problem Understanding
                        </h4>
                        <p className="text-muted-foreground leading-relaxed">
                          {approach.problem_understanding}
                        </p>
                      </div>
                    )}

                    {approach.naive_vs_optimal && (
                      <div className="p-4 rounded-lg bg-muted/40 border">
                        <h4 className="font-semibold text-primary mb-1">Naive vs Optimal Comparison</h4>
                        <p className="text-muted-foreground leading-relaxed">
                          {approach.naive_vs_optimal}
                        </p>
                      </div>
                    )}

                    {approach.step_by_step_execution && Array.isArray(approach.step_by_step_execution) && (
                      <div className="p-4 rounded-lg bg-muted/40 border">
                        <h4 className="font-semibold text-primary mb-2">Step-by-Step Execution Sequence</h4>
                        <ol className="list-decimal list-inside space-y-1.5 text-muted-foreground">
                          {approach.step_by_step_execution.map((step: string, idx: number) => (
                            <li key={idx} className="pl-1">
                              <span className="text-foreground">{step}</span>
                            </li>
                          ))}
                        </ol>
                      </div>
                    )}

                    {approach.time_and_space_complexity && (
                      <div className="p-4 rounded-lg bg-primary/5 border border-primary/20">
                        <h4 className="font-semibold text-primary mb-1">Time & Space Complexity</h4>
                        <p className="font-mono text-xs text-foreground">
                          {approach.time_and_space_complexity}
                        </p>
                      </div>
                    )}
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">No approach metadata recorded.</p>
                )}
              </TabsContent>

              {/* Parameters Tab */}
              <TabsContent value="parameters">
                {extractedParameters ? (
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                    <div className="p-4 rounded-lg border bg-card">
                      <div className="text-xs text-muted-foreground font-medium mb-1">Algorithm / Topic</div>
                      <div className="font-bold text-base text-primary">
                        {extractedParameters.algorithm_or_topic || topic}
                      </div>
                    </div>

                    <div className="p-4 rounded-lg border bg-card">
                      <div className="text-xs text-muted-foreground font-medium mb-1">Parsed Input Dataset</div>
                      <div className="font-mono text-xs bg-muted p-2 rounded break-all">
                        {extractedParameters.input_data
                          ? JSON.stringify(extractedParameters.input_data)
                          : "Auto-generated default"}
                      </div>
                    </div>

                    <div className="p-4 rounded-lg border bg-card">
                      <div className="text-xs text-muted-foreground font-medium mb-1">Target / Goal Value</div>
                      <div className="font-mono text-xs bg-muted p-2 rounded">
                        {extractedParameters.target_value !== undefined
                          ? String(extractedParameters.target_value)
                          : "None"}
                      </div>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">No parameters metadata recorded.</p>
                )}
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
